development:
  dialect: postgres
  datasource: host=localhost port=5432 dbname=garadb user=postgres password=1234 sslmode=disable
  dir: migrations
  table: gorp_migrations

test:
  dialect: postgres
  datasource: root:root@tcp(127.0.0.1:33062)/bookdb?parseTime=true
  dir: migrations
  table: gorp_migrations