version: "3"

services:
  db:
    image: postgres:16.3
    container_name: ${DB_NAME}
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db:/var/lib/postgresql/data

  redisDB:
    image: redis:7.4-rc1
    restart: always
    container_name: ${REDIS_NAME}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DATABASES: 16
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis:/data

volumes:
  db:
  redis:
